### ISSUE TITLE
Scala native support

### ISSUE THREAD

**Issue by alexarchambault** [lihaoyi/utest#110]
I know there's a scala-native port of utest out there (https://github.com/scala-native-ports/utest). Are there plans to support it from here? So that it can be published along the official JARs in particular.

cc @MasseGuillaume

**Comment by MasseGuillaume** [comment]
@Duhemm will add testing framework support. (sbt test interface)

utest compiles and link: https://github.com/scala-native/scala-native/issues/435

**Comment by xuwei-k** [comment]
FYI https://github.com/scalaprops/scalaprops/issues/30

**Comment by japgolly** [comment]
If a PR appears that works 100%, I'll be happy to merge and maintain it.
If support is partial then I'd prefer including it to hold off until it's stable (at as in terms of being on `master` and being published)

**Comment by alexarchambault** [comment]
Closing, as `0.4.8` supports native.
