### ISSUE TITLE
Improvements for Scala Native support

### ISSUE THREAD

**Issue by ekrich** [lihaoyi/utest#118]
Thanks for the recent Scala Native support. The following shows a couple of use cases that would help make writing tests with utest better.

For example the following does not work.
```
package example

import utest._
import scala.scalanative.native._

object NativeTest2Suite extends TestSuite {
  val tests = this {
    val f = stackalloc[CFloat]
    !f = 1.0f
    val ff = !f
    val d = 3.0

    'test {
      // ok
      assert(d == 3.0)
      // ok
      assert(ff == 1.0)
      // fails here - Tag[T] required?
      assert(!f == 1.0)
    }
  }
}
```
But this works fine in a basic application.
```
package example

import scala.scalanative.native._

object ClosureTest extends App {
  val f = stackalloc[CFloat]
  !f = 1.0f

  def foo {
    // ok
    println(s"f = ${!f}")
    assert(!f == 1.0)
  }
  foo
}
```
Also, you can not use `Zone`s other than inside a test. Example place you might want a `Zone` is commented out.
```
package example

import utest._
import scala.scalanative.native._

object NativeTest1Suite extends TestSuite {

  def tests = this {
    //Zone { implicit z =>
      // do stuff in Zone here
      'test {
        // ok for Zone here
        Zone { implicit z =>
          val f = alloc[CFloat]
          !f = 1.0f
          assert(!f == 1.0)
        }
      }
    //}
  }
}
```

**Comment by frgomes** [comment]
@ekrich : I've observed that uTest not always deliver what we expect.

I haven't tried your code, but I guess that ``assert(!f == 1.0f)`` is not really "ready for the assertion". Sorry for the imprecision of this claim. You will understand soon below.

I would do this way:

```scala
val expected = 1.0f
val actual = !f
assert(expected == actual)
```
Sorry, but my pragmatism (or laziness, if you will) prevented me of investigating why this sort of boilerplate is desirable or even needed. I've just observed that this sort of boilerplate always works. And I always to that way without questioning. This sort of boilerplate is what I meant by "ready for the assertion".

**Comment by ekrich** [comment]
Well, I didn't look at utest but my guess is that the macros in utest do not allow in scope implicits into the closure and for sure it does not allow Zone inside the test as that will not compile.

**Comment by frgomes** [comment]
@ekrich : I guess that it will work if you assign whatever it is to a variable before the assertion. I mean: never pass expressions to be evaluated to ``assert``, not even ``!f``. It's ok to pass ``f``, but not ``!f``.

**Comment by lihaoyi** [comment]
uTest's assert macros do funky things to automatically print out things on failure; you are probably seeing it mess with scala-native's own special handling of `!f` when it becomes `!printThingOutOnFailure(f)` or something

**Comment by lihaoyi** [comment]
Also, `'test{}` blocks have to be directly nested in each other; you can't put them nested within other things. That's just the way uTest works: test blocks are discovered at compile time, not runtime

**Comment by ekrich** [comment]
@lihaoyi and @frgomes. Thanks for taking a look. I'm pretty sure we can have a better experience using Scala Native so maybe the experts in Scala Native can add something to this discussion.

**Comment by lihaoyi** [comment]
Closing this for now since there's no real issue that can be fixed here
