### ISSUE TITLE
Publish a version for 2.13.0-M2

### ISSUE THREAD

**Issue by alexarchambault** [lihaoyi/utest#121]
It seems only 2.13.0-M1 is supported for now. But some other projects (scala-js in particular) seem to only support 2.13.0-M2 in their latest versions, which prevents using them along with utest.

**Comment by lihaoyi** [comment]
Necessary code changes went in in https://github.com/lihaoyi/utest/commit/bd31491a26c1e78486dc1fdff867e5ebcae078f7, next release should include 2.13.0-M2 artifacts for scala-jvm and scala-js
