### ISSUE TITLE
Deprecate `* - {}` in favor of `test {}` for anonymous tests

### ISSUE THREAD

**Issue by olafurpg** [lihaoyi/utest#127]
See discussion: https://www.reddit.com/r/scala/comments/71nqix/utest_the_essential_test_framework_for_scala_blog/dnh7f9l/

```scala
// before
* - check()
// after
test { check() }
// maybe with language.postFix
test check()
```

It should be possible to automate most of the migration, a simple sed script might get us quite far but I'm also happy to provide a scalafix migration rewrite.

**Comment by lihaoyi** [comment]
For context, this would also change:

```scala
"foo bar" - {
  ...
}
```

to

```scala
test("foo bar"){
  ...
}
```

The reasoning for this change is that we want to minimize the number of magic-DSLs that uTest provides. uTest prides itself on having less magic DSLs that e.g. ScalaTest or Specs2, but this `'foo -{}` `"foo" - {}` `* - {}` syntax remains.

There was no real reason why `"foo" - {}` was chosen: that was simply the syntax for ScalaTest's FreeSpec, which I was using before the uTest project was started, and so uTest copied it. 

Writing things out explicitly as `test("foo"){...}` blocks is a bit more verbose, but definitely a lot less magic-DSL-y. It also offers some extensibility e.g. if we want to add metadata to individual tests or blocks, we can do so by passing additional arguments to the call e.g. `test("foo", tag="slow"){...}`

I wouldn't even bother with a migration - a plain old deprecate-and-advertise-the-new-syntax is enough. People can update to the new syntax at their leisure.

**Comment by frgomes** [comment]
I find this convenient that uTest mimics this ScalaTest syntax.
Reason: migration path. People aware of uTest but not allowed to use it for whatever reason may write code which later can be compiled with uTest easily. The opposite is obviously true as well.

Or it was... I haven't tried such migration path after 0.5.0.

**Comment by olafurpg** [comment]
@frgomes I used this small helper to port my FunSuite tests to utest, made migration quite easy. 

```scala

import utest._, framework._

trait FunSuite extends TestSuite {
  private val myTests = IndexedSeq.newBuilder[(String, () => Unit)]
  def test(name: String)(fun: => Any): Unit = {
    myTests += (name -> (() => fun))
  }
  final override def tests: Tests = {
    val ts = myTests.result()
    val names = Tree("", ts.map(x => Tree(x._1)): _*)
    val thunks = new TestCallTree(Right(ts.map(x => new TestCallTree(Left(x._2())))))
    Tests.apply(names, thunks)
  }
}
```

**Comment by frgomes** [comment]
@olafurpg : thanks for the code snippet. And I'm sorry for the very late reply.

What I mean is that uTest is particularly very convenient for me. Why? Because I used to employ ``FreeSpec`` in past. If, for whatever reason I'm obliged to use ScalaTest... guess what... FreeSpec without any doubt, since I can easily throw away ScalaTest on a later date.
