### ISSUE TITLE
publish for Scala 2.13.0-M2, please

### ISSUE THREAD

**Issue by SethTisue** [lihaoyi/utest#128]

**Comment by lihaoyi** [comment]
I don't remember publishing it, but it seems to already be published on maven central... https://search.maven.org/#search%7Cga%7C1%7Cutest

**Comment by SethTisue** [comment]
sorry, I don't know how I missed that. thanks... added to https://github.com/scala/make-release-notes/blob/2.13.x/projects-2.13.md

**Comment by lihaoyi** [comment]
Haha don’t feel bad, I missed it too and I was the one who published it...
