### ISSUE TITLE
Cannot run test inside IDEA

### ISSUE THREAD

**Issue by jcranky** [lihaoyi/utest#129]
When trying to run or debug a test inside IDEA I'm getting this:

```scala
Testing started at 20:42 ...
Exception in thread "main" java.lang.ClassNotFoundException: utest.framework.TestTreeSeq
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.jetbrains.plugins.scala.testingSupport.uTest.UTestRunner.main(UTestRunner.java:316)

Process finished with exit code 1
```

The test works perfectly when running directly from sbt. Perhaps this is an IDEA issue, not a uTest one?

**Comment by lihaoyi** [comment]
Sounds like https://youtrack.jetbrains.com/issue/SCL-12660. Could you try their latest EAP?

**Comment by jcranky** [comment]
It definitely looks like that one, thanks for the pointer. I'll try the EAP later :)

**Comment by aggenebbisj** [comment]
I'm using one of the latest versions of IntelliJ, but it still doesn't seem to work. Can this issue be reopened?

Details:
IntelliJ IDEA 2017.3 EAP (Ultimate Edition)
Build #IU-173.3415.22, built on October 25, 2017
IntelliJ IDEA EAP User
Expiration date: November 24, 2017
JRE: 1.8.0_152-release-1024-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by lihaoyi** [comment]
are you on the latest version of the *Scala Plugin*? I think it's versioned separately from IntelliJ IDEA itself

**Comment by aggenebbisj** [comment]
I was on version `Version: 2017.3.4` and just updated to `Version: 2017.3.5`. Now it works. Was confused by the message in the referenced thread on the IntelliJ issue tracker which stated

> Try it please on latest Scala plugin EAP #2017.2.11.9. It's expected to be fixed there.

Thought 2017.3.4 was new enough. Thanks for the quick reply though!
