### ISSUE TITLE
[question] utest adapter for junit?

### ISSUE THREAD

**Issue by wisechengyi** [lihaoyi/utest#140]
Hi @lihaoyi,

I search around the doc but did not find related info, and was wondering if there is an adapter so utest can be run like junit test? The goal is hook it up our existing junit runner.

For example like scalatest:
```
import org.junit.runner.RunWith
import org.scalatest.WordSpec
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class WelSpec extends WordSpec {
  ...
}
```

If yes, could you kindly share the doc/steps? If not, what/how much work do you think is needed?

Thanks,
Yi

**Comment by lihaoyi** [comment]
Questions should go in the gitter room, not the issue tracker
