### ISSUE TITLE
Cannot link error with scala-native

### ISSUE THREAD

**Issue by alexarchambault** [lihaoyi/utest#144]
Systematically getting some "cannot link" errors when trying to run tests with scala native, like
```
[error] cannot link: @java.lang.Class::getField_java.lang.String_java.lang.reflect.Field
[error] cannot link: @java.lang.ClassLoader::loadClass_java.lang.String_java.lang.Class
[error] unable to link
```

These seem to happen at least since scala-native >= 0.3.3. Tried with various combinations (not all though) of sbt-scala-native (0.3.3 -> 0.3.6), sbt (0.13.16, 1.0.4), and utest (0.4.8, 0.5.4, 0.6.3), same error.

Full repro: https://github.com/alexarchambault/utest-native-issue

**Comment by piotrkwiecinski** [comment]
@alexarchambault parts of SN are still not implemented and are marked as stubs.

As a reference check https://github.com/lihaoyi/utest/blob/master/build.sbt#L71:L77

This should solve your problem.

**Comment by alexarchambault** [comment]
Ok, `nativeLinkStubs := true` solves it. Thanks @piotrkwiecinski!
