### ISSUE TITLE
Add support for scala 2.13.0-M3

### ISSUE THREAD

**Issue by alexarchambault** [lihaoyi/utest#159]

**Comment by SethTisue** [comment]
2.13.0-M4 is out now.

the Scala 2.13 community build shows that the new collections landing means some changes are needed here. I'm seeing compile errors such as:

```
[utest] [error]  found   : scala.collection.mutable.Buffer[utest.framework.Tree[String]]
[utest] [error]  required: Seq[utest.framework.Tree[String]]
[utest] [error]     for (grouping <- ordered) yield {
```

because default `Seq` is now immutable, and

```scala
[utest] [error] /Users/tisue/community.213/target-0.9.12/project-builds/utest-0ca1a9d492311923bb1834281006436668721bd4/utest/shared/src/main/scala/utest/TestRunner.scala:206: value appendAll is not a member of scala.collection.mutable.Buffer[Seq[String]]
[utest] [error]       case Left(l) => left.appendAll(l)
[utest] [error]                            ^
```

because `appendAll` is called something else now.

**Comment by SethTisue** [comment]
is there a volunteer who could work on this...?

**Comment by alexarchambault** [comment]
If no one peeks that in the mean time, me… around September / October!

**Comment by dwijnand** [comment]
https://github.com/lihaoyi/utest/pull/163 makes the code changes, but not the build changes.

**Comment by SethTisue** [comment]
is there some we can move forward on this..? anyone available to tackle it?

**Comment by SethTisue** [comment]
Scala 2.13.0-M5 is now out

**Comment by japgolly** [comment]
I'm not putting my hand up to make these changes but if someone else is able to contribute a PR, I can put my hand up to do the review and merge. I completely forgot that I'm a maintainer of utest :laughing:
