### ISSUE TITLE
Reflect test structure in output

### ISSUE THREAD

**Issue by bwbecker** [lihaoyi/utest#161]
One of the things I love about uTest is the nested structure of the tests.  It allows for easy and intuitive grouping of related tests.

If I'm not mistaken, earlier versions of uTest reflected that structure in the output.  I miss that and think that not reflecting it is a missed opportunity.

I've overridden `formatSingle(path: Seq[String], r: Result): Option[Str]` to produce output such as the following.

```
tracing
  TracingFutureTests
    mapT should
+     map success 13ms  
+     map failure should include extra info 7ms  
+     work with normal map but loses information 1ms  
    
    flatMapT should
+     succeed 1ms  
+     flat map a failure 1ms  
    
    for comprehension should
+     succeed 1ms  
+     handle a failure in the last future 1ms  
+     handle a failure in the middle future 1ms  
+     handle a failure in the first future 1ms  
```
 
It works, but feels like a hack.  I'd love a better solution.

**Comment by lihaoyi** [comment]
By default uTest now only prints the hierarchical test summary if there's > 30 tests in total; the reasoning is that if you're running just e.g. 4 tests then repeating the whole listing is verbose and unnecessary.

You can change the threshold by overriding a field on the `Framework` class
