### ISSUE TITLE
Allow ? in addition to - for tests that must be explicitly invoked

### ISSUE THREAD

**Issue by benjaminjackman** [lihaoyi/utest#17]
`?` could be added in addition to `-` on the string/symbol implicits to indicate that a test should be ignored unless specifically called, this is useful to when you are iterating on development, or when you want to show a particular feature.

Also if a test is failing for a known reason you want to defer until later you can flip it off by using this as well, it's really easy to just flip the - to a ?.

This is roughly equal to using `@ignore` `explicit` in other frameworks

(http://www.nunit.org/index.php?p=explicit&r=2.4.8)

**Comment by dvtomas** [comment]
I found a solution to this without having to enhance uTest.

Just define something like
```scala

def pending(action: ⇒ Unit): Unit = {
  try {
    action
  } catch {
    case _: AssertionError ⇒
  }
}
```

Now you can easily turn a test into pending using
```scala
"testFoo" - pending {
...
}
```

Nice & clean, IMHO :) You can even have different flavors - one running the test, but catching assertions, other not running it at all.

**Comment by lihaoyi** [comment]
Gonna just declare bug bankruptcy on this one

**Comment by frgomes** [comment]
@dvtomas : Thanks for your idea.

This thing below works well enough for me, except that I'd like to see an yellow marker, instead of a false positive green.
```scala
import com.typesafe.scalalogging.StrictLogging
trait uTestActions extends StrictLogging {
  def ignore(action: ⇒ Unit): Unit = ignore
  def pending(action: ⇒ Unit): Unit = {
    try {
      action
    } catch {
      case t: Throwable => pending(t)
    }
  }

  private def ignore: Unit = {
    val t = new RuntimeException
    val it = t.getStackTrace.iterator
    val e = (1 to 5).map(_ => it.next).last
    report("IGNORE", e)
  }

  private def pending(t: Throwable): Unit = {
    val pos = t.getStackTrace.zipWithIndex.find(p => p._1.getMethodName == "pending").get._2
    val it = t.getStackTrace.iterator
    val e = (1 to pos+4).map(_ => it.next).last
    report("PENDING", e)
  }

  private def report(state: String, e: StackTraceElement): Unit = {
    val _class  = e.getClassName
    val _method = e.getMethodName
    val _file   = e.getFileName
    val _line   = e.getLineNumber
    logger.error(s"@@@@@@@@ ${state}:: ${_class}.${_method} at ${_file}:${_line}")
  }
}
```
