### ISSUE TITLE
publish for Scala 2.13.0-M5?

### ISSUE THREAD

**Issue by SethTisue** [lihaoyi/utest#183]
I was able to do `++2.13.0-M5!` followed by `utestJVM/test` locally, so perhaps no code changes are needed and it's just a matter of pulling the release levers...?

**Comment by olafurpg** [comment]
utest v0.6.6 is out with support for 2.13.0-M5

```
+ coursier fetch com.lihaoyi:utest_2.13.0-M5:0.6.6 -r sonatype:releases
https://oss.sonatype.org/content/repositories/releases/com/lihaoyi/utest_2.13.0-M5/0.6.6/utest_2.13.0-M5-0.6.6.pom
  100.0% [##########] 2.3 KiB (3.8 KiB / s)
```

The utestJS release on Scala.js 1.0.0-M5 did not succeed on 2.13.0-M5 due to resolution errors 

```
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.scala-js#scalajs-library_2.13.0-M5;1.0.0-M5: not found
```

**Comment by SethTisue** [comment]
scala/make-release-notes@2dbaaee7cdb9bc69da842cb5f224f79e92046dce
