### ISSUE TITLE
wrong "Results" summary for "fork:=true"

### ISSUE THREAD

**Issue by vn971** [lihaoyi/utest#25]
Hi! I just created an empty project, copy-pasted a demo Test, but I'm getting a wrong "Results" summary.

Code:

```
package net.pointsgame.debug

import utest._

object MyTest extends TestSuite {
    val tests = TestSuite {

        'fakeTest {
            assert(1 == 1)
        }

    }
}
```

Console output:

```
[info] 1/2     net.pointsgame.debug.MyTest.fakeTest     Success
[info] 2/2     net.pointsgame.debug.MyTest      Success
[info] -----------------------------------Results-----------------------------------
[info] 
[info] Tests: 0
[info] Passed: 0
[info] Failed: 0
[success] Total time: 5 s, completed Jun 12, 2014 3:12:29 AM
```

Were there any recent changes that may have broken the "Results" summary?

**Comment by ddispaltro** [comment]
I just ran into this, any ideas?

**Comment by lihaoyi** [comment]
I ran into this too. Haven't had a chance to dig into it

**Comment by wwagner4** [comment]
Have the same problem

**Comment by wwagner4** [comment]
What I found out is: SBT creates two instances of MasterRunner. Then calls 'tasks' on one and 'done' on the other.

**Comment by lihaoyi** [comment]
Should be fixed by https://github.com/lihaoyi/utest/commit/46c3b05e9ab70fb0e048dd11d99672050709d373
