### ISSUE TITLE
print matched value for assertMatch

### ISSUE THREAD

**Issue by antonkulaga** [lihaoyi/utest#32]
When I do assertMatch, make sbt test and it fails I get something like "    Failure(utest.AssertionError: (assertMatch(new TestTermParser("http://google.com.ua").IRI_REF.run()){case Success(IRI("http://google.com.ua"))=>}"

But I do not see the actual value of matched variable. That is why I have to add additional lines to see the real value before assertMatch when test fails. It would be great (and would save some time) if together with assertion failure it also printed toString value of the variable.

**Comment by lihaoyi** [comment]
Fixed in 

69dbec6
--
