### ISSUE TITLE
Add support for Custom test configuration

### ISSUE THREAD

**Issue by l15k4** [lihaoyi/utest#42]
Hi,

I'm trying to create multiple test configurations because async tests require PhantomJS(autoExit =false), but I think that utest doesn't support setting a filter in `testOptions`, at least I couldn't figure that out. I was playing with this setup : 

```
  lazy val AsyncTest = config("async") extend(Test)

  lazy val js =
    project.in(file("js"))
      .configs(AsyncTest)
      .settings(scalaJSSettings:_*)
      .settings(utestJsSettings:_*)
      .settings(inConfig(AsyncTest)(Defaults.testSettings ++ utestJsSettings) :_*)
      .settings(
        persistLauncher in AsyncTest := false,
        testOptions in AsyncTest := Seq(Tests.Filter(s => s.contains("Async"))),
        postLinkJSEnv in AsyncTest := new PhantomJSEnv(autoExit = false),
       )
```

But the `testOptions` never works, either all tests are executed or none is.

Do you have any idea how to make it work, or what might be the problem ?

**Comment by nafg** [comment]
FWIW here's the link to SBT docs on `testOptions`: http://www.scala-sbt.org/0.13/docs/Testing.html#Options
