### ISSUE TITLE
Tests using scalatags

### ISSUE THREAD

**Issue by Kyprus** [lihaoyi/utest#47]
I have a test in my scalajs project that calls code that creates an image element using scalatags and the DOM renderer.. When I try to run the test I get a big stacktrace with `TypeError: Cannot call method "createElementNS" of undefined` at the top. Sounds like there is no DOM? I'm not sure what is going on.

Thanks!

**Comment by lihaoyi** [comment]
try using `requiresDOM := true` as shown in http://www.scala-js.org/news/2014/06/13/announcing-scalajs-0.5.0/?

**Comment by Kyprus** [comment]
That worked. I figured I was missing something. Thanks!
