### ISSUE TITLE
please don't output special characters

### ISSUE THREAD

**Issue by fommil** [lihaoyi/utest#50]
(it may sound weird that I can report this bug in the light of #49, but utest can run my tests if I have a pure JVM project.)

I do all my editing and use of sbt via emacs (and ENSIME). The output of sbt is displayed in a buffer and special characters are not interpreted by default (the typical emacs philosophy is to enrich output by parsing it and adding faces/links/functions to special regions)

Hence, my tests look like this

```
[info] -----------------------------------Results-----------------------------------
[info] com.github.fommil.kerbal.SolverSpec		32mSuccess0m
[info]     should solve for a Kerbin to Mun 10 payload		32mSuccess0m
[info] com.github.fommil.kerbal.EngineSuite		32mSuccess0m
[info]     should return valid fuel tanks for the Poodle engine		32mSuccess0m
[info]     should return valid fuel tanks for the KR-1x2 engine		32mSuccess0m
[info] Failures:
```
where `32mSuccess0m` is pretty ugly.

**Comment by lihaoyi** [comment]
Running it with `--color=false` should turn them off

**Comment by fommil** [comment]
uuugh, can't you make no colour the default? Or set this in the build.sbt?

**Comment by fommil** [comment]
or, better, detect the $TERM and don't output special chars if it's a dumb terminal

**Comment by lihaoyi** [comment]
> Or set this in the build.sbt? 

Maybe, want to send a PR? In general all the settings could be settable in the build.sbt, but I haven't done that yet= P

**Comment by lihaoyi** [comment]
Detecting $TERM seems sketchy. What happened to unix-philosophy-dumb-pipes!

**Comment by fommil** [comment]
most apps detect if the terminal/pipe can handle the special chars. I'm not sure how they do it, but I've certainly looked to see if $TERM can handle it. I don't think the colour works in Windows, for example.
