### ISSUE TITLE
--color=false ignored in Js Runner

### ISSUE THREAD

**Issue by fommil** [lihaoyi/utest#51]
you close #50 but I found a bug in your workaround :wink:

As the title says, passing `--color=false` to the tests, when run on Rhino, is ignored.

To see, run `sbt test` on my project https://github.com/fommil/kerbal-calculator and see that no special characters are printed in the JVM project, but special characters are printed in the Rhino run.

This branch definitely exhibits it: https://github.com/fommil/kerbal-calculator/tree/a431c0a7e110faa7bb864c290de1cc7503ad8a4a

**Comment by fommil** [comment]
hold on, I don't see how it could ever work... the `color: Boolean` flag is ignored most of the time!

* https://github.com/lihaoyi/utest/blob/master/js/shared/main/scala/utest/framework/Formatter.scala#L44
* https://github.com/lihaoyi/utest/blob/master/js/shared/main/scala/utest/framework/Formatter.scala#L58

**Comment by fommil** [comment]
more ignoring of `color: Boolean`:

https://github.com/lihaoyi/utest/blob/e15d69a5addccb423a235010cd7830168e4c3e83/js/shared/main/scala/utest/runner/MasterRunner.scala#L47

**Comment by lihaoyi** [comment]
lol, that's what happens when you don't add unit tests for something

**Comment by fommil** [comment]
thank goodness you can run the tests of your tests with colour in your terminal. I'd be stuck in an infinite catch 22 unable to see the answers!

**Comment by lihaoyi** [comment]
Fixed in the WIP `test` branch targeting 0.4.0
