### ISSUE TITLE
not supported on Java 6

### ISSUE THREAD

**Issue by fommil** [lihaoyi/utest#52]
one can expect to see this sort of stack trace on Java 6 as you're relying on a constructor that was added in JDK6:

```
java.lang.NoSuchMethodError: java.lang.AssertionError: method <init>(Ljava/lang/String;Ljava/lang/Throwable;)V not found
	at utest.AssertionError.<init>(Errors.scala:25)
	at utest.asserts.package$.assertError(package.scala:19)
```

**Comment by lihaoyi** [comment]
With Scala 2.12 and Java 9 coming out some time, this is probably gonna be a wontfix for now...
