### ISSUE TITLE
failures not reported

### ISSUE THREAD

**Issue by fommil** [lihaoyi/utest#53]
This is the summary of my test run:
```
[info] Tests: 5
[info] Passed: 4
[info] Failed: 1
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
```

It looks like the aggregate is ignoring the individual scores.

**Comment by lihaoyi** [comment]
You're using `fork:=true` right? I think this should be fixed by the latest master but I haven't verified

**Comment by lihaoyi** [comment]
This isn't fixed. In fact it's super annoying

**Comment by lihaoyi** [comment]
Same as #25
