### ISSUE TITLE
Changes for SJS 0.6.0?

### ISSUE THREAD

**Issue by jokade** [lihaoyi/utest#57]
Sorry if I missed it in the docs... but what has changed in the required config for using utest 0.3.0 with SJS 0.6.0? Obviously, there is no utest sbt plugin anymore (?); but after I've I added the utest library dependency and the `new TestFramework(...)` entry to my build.sbt, my test cases aren't executed anymore. BTW: I've upgraded from utest 0.2.5-RC1.

**Comment by lihaoyi** [comment]
crossProject requires a different folder layout from the old cross build;
perhaps you still have your files in the old places?

**Comment by lihaoyi** [comment]
lol now i'm seeing the same problem... i hope i didn't botch anything

**Comment by lihaoyi** [comment]
Could this be your problem?

```diff
-  testFrameworks += new TestFramework("utest.runner.JvmFramework"),
+  testFrameworks += new TestFramework("utest.runner.Framework"),
```

**Comment by jokade** [comment]
No, I'm already using `utest.runner.Framework`, and it's not a cross build project; however, it's a multi-project build with the tests in a separate project (testing macros) -- could this be a problem?

**Comment by lihaoyi** [comment]
It shouldn't be. Do you have a link to the project repo?

**Comment by jokade** [comment]
It’s this branch: https://github.com/jokade/scalajs-angulate/tree/issue28 <https://github.com/jokade/scalajs-angulate/tree/issue28>

> Am 06.02.2015 um 08:01 schrieb Li Haoyi <notifications@github.com>:
> 
> It shouldn't be. Do you have a link to the project repo?
>

**Comment by japgolly** [comment]
I believe this can be closed now. SJS 0.6 is supported and widespread.
