### ISSUE TITLE
uTest interacts badly with Angular.js?

### ISSUE THREAD

**Issue by giovannicandido** [lihaoyi/utest#64]
I cannot run tests with angularjs as dependency:

jsDependencies ++= Seq (
    "org.webjars" % "angularjs" % "1.3.14" / "angular-route.js" dependsOn "angular.js",
    "org.webjars" % "angularjs" % "1.3.14" / "angular.js"
 )

The problem returned is org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: PhantomJS exited with code 2

When using without  jsDependencies += RuntimeDOM the nodejs process return exit 1. Comment the dependencies work and the test run

**Comment by easel** [comment]
Did you ever resolve this issue? I'm seeing the same error and have angular in my stack as well. Removing angular resolves the issue.

**Comment by maprohu** [comment]
I had something similar. 

Including the minified version of angular resolved the issue for me:

jsDependencies += "org.webjars" % "angularjs" % "1.4.4" / "angular.min.js"
