### ISSUE TITLE
java.lang.IllegalArgumentException: Could not find proxy

### ISSUE THREAD

**Issue by betehess** [lihaoyi/utest#65]
This compiles and runs as expected:

```scala
"the comment" - { assert(true) }
```

but the following

```scala
val comment = "the comment" 
comment - { assert(true) }
```

fails at compile time with an error that look like that:

```
[error] (ldpatchJVM/test:compile) java.lang.IllegalArgumentException: Could not find proxy for val comment: String in List(value comment, method positiveEvaluationTest, method tests, class LDPatchTestSuite, package ldpatch, package banana, package w3, package org, package <root>) (currentOwner= method tests )
```

I need to generate tests from external files, so their names are not known at compile time. Is that a limitation of utest?

**Comment by lihaoyi** [comment]
Yeah it's a limitation of uTest. All test names have to be present in the file at compile time. If you want to run a bunch of dynamic asserts, you'll need to put them all in one big test
