### ISSUE TITLE
lazy vals crash compiler

### ISSUE THREAD

**Issue by japgolly** [lihaoyi/utest#67]
Yo. It seems `lazy val`s within tests crash scalac.
It happens when compiling for JVM and JS.

Reproduction:

``` scala
object What { def mf1 = 2 }
object SomeTest extends TestSuite {
  override def tests = TestSuite {
    import What._
    lazy val subj = mf1
  }
}
```

You can see big error messages if you want in https://github.com/scala-js/scala-js/issues/1580

**Comment by lihaoyi** [comment]
This should be fixed in Scala 2.12.x in https://github.com/lihaoyi/utest/commit/36c2c3d4e5323f7512689bf98ae78bda7c393094, enforced in https://github.com/lihaoyi/utest/commit/c1799d2faa4294c52f1fff27399d76b2bb537fe3
