### ISSUE TITLE
Compiler crash caused by an edge case in TestSuite

### ISSUE THREAD

**Issue by jducoeur** [lihaoyi/utest#70]
The following code is a bit obscure, but minimized from a real test I was playing with:

```
package querki.test

import scala.concurrent.Future
import utest._

object FutureCrashTest extends TestSuite {
  def wrapping[T](f: => T):T = {
    f
  }
  implicit val queue = scala.scalajs.concurrent.JSExecutionContext.Implicits.runNow

  def tests = TestSuite {
    "Crash the compiler when I spew a future" - {
      wrapping { val fut = Future { 1 } }
      // println("This prevents the crash")
    }
  }
}
```

Not quite sure what's going on -- the problem only seems to happen when I have this "wrapping" function that is invoking some code which creates but does _not_ return a Future, at the end of a test.  Changing this in almost any way (including uncommenting that last line) causes the problem to go away.

Trying to compile this results in an internal compiler assertion that indicates that the resulting tree is somehow illegal, as seen in [this gist](https://gist.github.com/jducoeur/2b6cc78b4033230e5956).

While the above example is from ScalaJS, this code (with the queue changed appropriately) also fails to compile with a similar assertion on ScalaJVM, so it appears that utest is doing something illegal in this edge case.

**Comment by lihaoyi** [comment]
No idea when this was fixed, but https://github.com/lihaoyi/utest/commit/473a360e654d031ee3762391c52ec88078b79a1a checks that it works. Tested manually to work in 2.10.6, 2.12.3, Scala-JVM and Scala.js
