### ISSUE TITLE
How to share tests?

### ISSUE THREAD

**Issue by japgolly** [lihaoyi/utest#74]
Say you have two test cases and 50% of the tests are the same, just with different types & impls, how can tests be shared without copy & pasting?

Like ideally it'd be useful to have something like this:
```scala
def sharedTests[A: Plus](a: A, b: A, sum: A) = {
  "a+b=s" - assert(a + b == sum)
  "b+a=s" - assert(b + a == sum)
}

object Int extends TestSuite {
  override def tests = {
    'blah1 - assert(whatever)
    'blah2 - assert(whatever)
    sharedTests[Int](3, 7, 10)
  }
}
```

Is the possible? If not do you know how much work it'd take to make it work?

**Comment by lihaoyi** [comment]
Traditionally I've done this via inheritance

```scala
class SharedTests[A: Plus](a: A, b: A, sum: A) extends TestSuite{
  val tests = TestSuite{
    "a+b=s" - assert(a + b == sum)
    "b+a=s" - assert(b + a == sum)
  }
}
object Int extends SharedTests[scala.Int](3, 7, 10)
object Long extends SharedTests[scala.Long](3L, 7L, 10L)
```

**Comment by japgolly** [comment]
With that approach you can't add new tests or use multiple shared suites.

**Comment by lihaoyi** [comment]
Put them in separate top level objects; not too bad =P objects in Scala are
cheap

**Comment by japgolly** [comment]
Hrm, that's a bit messy. Things will all be spread out but yeah, that'll
work :)

**Comment by lihaoyi** [comment]
Put them in the same file. This isn't Java =D

**Comment by lihaoyi** [comment]
Check out the Scalatags test suite, which makes ridiculously heavy use of this to test both the `scalatags.Text` and `scalatags.JsDom` using the same test code!

https://github.com/lihaoyi/scalatags/tree/master/scalatags/shared/src/test/scala/scalatags/generic

**Comment by japgolly** [comment]
Cool I'll check it out. Thanks man
