### ISSUE TITLE
==> syntax instead of assert(___)

### ISSUE THREAD

**Issue by drhumlen** [lihaoyi/utest#75]
Would it be possible to add the `==>` that works *exactly* like assert? So that these two lines are equivalent:

```
assert(a.length == 10)

a.length ==> 10
```

I've tried to make an implicit conversion/class, but then it doesn't dump out what `a` is etc. You don't get that macro magic that you do with assert? Is there an easy way to do that already, or do you have to make a custom macro for that? Can you add it to µtest?

**Comment by lihaoyi** [comment]
Fixed in the WIP `test` branch targeting 0.4.0
