### ISSUE TITLE
Allow to use the test/Test configuration

### ISSUE THREAD

**Issue by mdedetrich** [lihaoyi/utest#78]
Currently, you are unable to use `uTest` with the test configuration due to https://groups.google.com/forum/#!msg/scala-js/WvFSrsDgGxo/blIlb4kwI44J
, i.e.
```sbt
"com.lihaoyi" %% "utest" % "0.3.1" % Test
```
or
```sbt
"com.lihaoyi" %%% "utest" % "0.3.1" % Test
```

Unfortunately this means that uTest will pollute our binary dependencies (and this prevents me from using uTest with https://github.com/json4s/json4s, since it needs to have strictly zero dependencies)

You should be able to use uTest as part of Test configuration

**Comment by lihaoyi** [comment]
What's wrong with 
```
"com.lihaoyi" %% "utest" % "0.3.1" % "test"
```
?

**Comment by lihaoyi** [comment]
@mdedetrich says it's not a problem
