### ISSUE TITLE
Enhancement: Expose utest.framework.TestPath to utestWrap

### ISSUE THREAD

**Issue by jk-1** [lihaoyi/utest#88]
This is enhancement proposal:

Allow using utest.framework.TestPath inside utestWrap function. This way it is possible to control wrapping functionality based on the test case.

Currently when I try to use  utest.framework.TestPath inside utestWrap function I get compiler error:

TestPath is only available within a uTest suite, and not outside.

Thank You!

**Comment by lihaoyi** [comment]
Seems plausible
