### ISSUE TITLE
Allow for additional output it assert

### ISSUE THREAD

**Issue by i-am-the-slime** [lihaoyi/utest#96]
I would really like to be able to provide a message that gets printed at the right place in the output when calling assert.

**Comment by lihaoyi** [comment]
Yes I'd like this too

**Comment by lihaoyi** [comment]
For now I'm going to punt on this and just say "use `Predef.assert` if you want to define the message"

It's possible there's some clever way to incorporate defining custom messages into the smart `utest.assert` we have now, but until then I think `Predef.assert` works ok
