### ISSUE TITLE
Show exception cause stack trace

### ISSUE THREAD

**Issue by hmil** [lihaoyi/utest#99]
A typical java exception consists of multiple nested exceptions establishing a chain of causality. It is printed like this by default:

```
Exception 1
[stack of exception 1]
Caused by: Exception 2
[stack of exception 2]
Caused by: ...
```

utest only shows the top-level stack trace (ie. everything above the first "Caused by") which in many cases is not enough to identify the source of the bug.

**Comment by lihaoyi** [comment]
Fixed in master in https://github.com/lihaoyi/utest/commit/8e2c06b8fe8091a2bc30552a3a00a803f8dd0ed6
